### ISSUE TITLE
github-bot comment only list the file but not list the formatted result

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/cpp-linter-action#19]
Refer to the screenshot. more details see this commit https://github.com/shenxianpeng/test-cpp-linter-action/commit/db1640735fec26e9b5b61c4c75403dce97d0028a

![image](https://user-images.githubusercontent.com/3353385/130396304-285749b1-e876-49f3-a2da-53d6c0ab0316.png)

Here is `yml` file (I'm not sure if I wrote the wrong `yml`)

```yml
name: cpp-linter

# Triggers the workflow on push or pull request events
on:
  push:
  pull_request:
jobs:
  cpp-linter:
    name: cpp-linter
    runs-on: ubuntu-latest
    steps:
      - name: C/C++ Lint Action
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: shenxianpeng/cpp-linter-action@master
        with:
          style: 'llvm'
          extensions: 'c'
          version: '11'
          
```

Expected result:

* if list the file, should also list the formatted result.
* otherwise do not add comment
